### ISSUE TITLE
请问现在可以贡献代码吗？

### ISSUE THREAD

**Issue by gawainGIT** [fgprodigal/RayUI#102]
收集了一些watcher用的法术id，想做点力所能及的事情，但是感觉应该等您结束了在进行。
要不然，不断相互同步会造成麻烦吧

**Comment by anson0370** [comment]
记得一直追赶主库 在PR之前记得rebase主分支就好（不了解rebase的话 看下git文档）

最好不要将主分支往你的PR分支上merge

**Comment by anson0370** [comment]
没有疑问的话 此 issue 关闭

**Comment by gawainGIT** [comment]
嗯，已经学会了
