### ISSUE TITLE
聊天框物品链接BUG

### ISSUE THREAD

**Issue by yakumo520** [fgprodigal/RayUI#12]
(http://img.ngacn.cc/attachments/mon_201610/30/a7Qhed-izq9K1jT1kSbd-4p.png)

[**描述**]
进入游戏任何频道物品链接或者成就链接鼠标移上去都是错误的，前面的时间也是0，或者在物品链接里会出现cffff等字样。

**重现Bug的步骤**

1. 第一步，进入游戏
2. 第二步，即会出现该情况
3. 第三步
4. 第四步

仅启用了RayUI，删除了WTF和Cache文件夹一样会重现该情况

**报错内容**
无报错内容

**Comment by tikkt** [comment]
按照你这个重现bug的步骤，并没有出现任何问题。好歹认真编辑下，发个了什么物品什么成就到什么频道，鼠标移上去怎么怎么样。至少也删除第三步第四步啊，好蛋疼，是不是傻

**Comment by yakumo520** [comment]
能加QQ聊聊么，特别喜欢这个插件，我第一次用这个提交bug，不是很懂，QQ249211396

**Comment by fgprodigal** [comment]
进入游戏，即会出现该情况。不好意思，我出现不了。去看看别人怎么提交bug的吧
