### ISSUE TITLE
一个小小诉求，关于对Angrystones的支持

### ISSUE THREAD

**Issue by LeonVons** [fgprodigal/RayUI#14]
水月君你好
    不知道您有没有使用过Angry Keystones这款插件呢？简单来说这是一款大秘境插件，功能有聊天框直接显示钥匙是哪个副本以及等级，小怪的鼠标提示显示击杀会获得多少进度，以及扩展任务追踪栏显示时间（总时间，3箱以及2箱时间）词缀死亡和BOSS击杀时间等详细的信息。我相信这是目前被使用的最广泛的一款大秘境插件，但是在同时使用此插件与Rayui时却出现了一个小小的冲突，时间的进度栏消失了。
    在此我自私的希望您能对此插件进行美化支持，下面我会放入两张图
![1](https://cloud.githubusercontent.com/assets/23161825/19845445/fef2cb44-9f71-11e6-8e12-04fefdf06005.png)
这是原始的样式。原谅我找了张比较模糊的图
![2](https://cloud.githubusercontent.com/assets/23161825/19845454/13e87ab2-9f72-11e6-9b77-b4eb0f1a0871.png)
这是使用rayui之后的图片，可以看到时间进度条被吃掉了- -只剩下两个竖杠，显得不是很直观突兀

**Comment by fgprodigal** [comment]
这插件只在大秘境里显示吗

**Comment by LeonVons** [comment]
对的，大秘境里显示在任务追踪栏上方的

**Comment by fgprodigal** [comment]
那这个难办，难以测试，首先我是只能打h5人本的菜逼，其次，测试不就浪费别人的钥匙和进度吗

**Comment by LeonVons** [comment]
- -婚后遁入休闲党了么
  也是，这玩意没有调试模式
  水月目前是在玩国服么，可以留战网，强力车队组你打钥匙啊

**Comment by fgprodigal** [comment]
还有，请先删除interface文件夹里除了addons文件夹的所以其他文件夹，我感觉你这是材质问题

**Comment by LeonVons** [comment]
确实如你所说，是[Auora Missing Textures材质包的问题！排查后把冲突的删了，OK！
对了，之前水月君在包里不是放了材质包么，怎么现在不用了
冲突的是挑战和方案，如果之后会放请注意这两个..
