### ISSUE TITLE
背包打不開

### ISSUE THREAD

**Issue by makcheunghei** [fgprodigal/RayUI#15]
找到問題了 不能覆蓋升級 請刪除這貼....

**Comment by fgprodigal** [comment]
请你按照提交bug的模板填写，谢谢，你这明显开了别的插件

**Comment by makcheunghei** [comment]
Message: ...ns\RayUI\libs\cargBags\mixins-add\rayui.scaffold.lua:3: Cannot find a library instance of "LibItemLevel.7000".
Time: 10/31/16 21:59:38
Count: 1
Stack: [C]: in function `error'
Interface\AddOns\RayUI\libs\LibStub\LibStub.lua:38: in function `GetLibrary'
...ns\RayUI\libs\cargBags\mixins-add\rayui.scaffold.lua:3: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibItemLevel.7000"."

這是載入的

**Comment by makcheunghei** [comment]
Message: ...ace\AddOns\RayUI\libs\cargBags\mixins\api-common.lua:85: attempt to call field '?' (a nil value)
Time: 10/31/16 22:00:18
Count: 1
Stack: ...ace\AddOns\RayUI\libs\cargBags\mixins\api-common.lua:85: in function `Scaffold'
...rface\AddOns\RayUI\libs\cargBags\base\itembutton.lua:80: in function `Create'
...rface\AddOns\RayUI\libs\cargBags\base\itembutton.lua:54: in function `New'
...e\AddOns\RayUI\libs\cargBags\base\implementation.lua:358: in function `UpdateSlot'
...e\AddOns\RayUI\libs\cargBags\base\implementation.lua:388: in function `UpdateBag'
...e\AddOns\RayUI\libs\cargBags\base\implementation.lua:413: in function `func'
...e\AddOns\RayUI\libs\cargBags\base\implementation.lua:226: in function `OnEvent'
...e\AddOns\RayUI\libs\cargBags\base\implementation.lua:81: in function `?'
Interface\AddOns\RayUI\libs\cargBags\base\core.lua:156: in function <Interface\AddOns\RayUI\libs\cargBags\base\core.lua:156>
[C]: in function `Show'
...e\AddOns\RayUI\libs\cargBags\base\implementation.lua:103: in function `Toggle'
Interface\AddOns\RayUI\libs\cargBags\base\core.lua:73: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: self = RayUI_ContainerFrameSlot1 {
 0 = <userdata>
 UpdateTooltip = <function> defined @Interface\FrameXML\BankFrame.lua:40
 GetInventorySlot = <function> defined @Interface\FrameXML\BankFrame.lua:533
 icon = RayUI_ContainerFrameSlot1IconTexture {
 }
 Count = RayUI_ContainerFrameSlot1Count {
 }
 IconBorder = <unnamed> {
 }
 IconQuestTexture = <unnamed> {
 }
 searchOverlay = RayUI_ContainerFrameSlot1SearchOverlay {
 }
 Cooldown = RayUI_ContainerFrameSlot1Cooldown {
 }
 SplitStack = <function> defined @Interface\FrameXML\BankFrame.lua:546
}
name = "ReagentBankItemButtonGenericTemplate"
(*temporary) = nil
(*temporary) = RayUI_ContainerFrameSlot1 {
 0 = <userdata>
 UpdateTooltip = <function> defined @Interface\FrameXML\BankFrame.lua:40
 GetInventorySlot = <function> defined @Interface\FrameXML\BankFrame.lua:533
 icon = RayUI_ContainerFrameSlot1IconTexture {
 }
 Count = RayUI_ContainerFrameSlot1Count {
 }
 IconBorder = <unnamed> {
 }
 IconQuestTexture = <unnamed> {
 }
 searchOverlay = RayUI_ContainerFrameSlot1SearchOverlay {
 }
 Cooldown = RayUI_ContainerFrameSlot1Cooldown {
 }
 SplitStack = <function> defined @Interface\FrameXML\BankFrame.lua:546
}
(*temporary) = "attempt to call field '?' (a nil value)"

這是開背包的

**Comment by makcheunghei** [comment]
除了RayUI和RayUI_Options 其他都沒載入 ADDONS其他都刪了

**Comment by LeonVons** [comment]
确实如你所说，是Auora Missing Textures材质包的问题！排查后把冲突的删了，OK！
对了，之前水月君在包里不是放了材质包么，现在怎么不用了
冲突的是Challenges和Scenarios，如果之后会放请注意这两个。。
