### ISSUE TITLE
3个小BUG 无报错的

### ISSUE THREAD

**Issue by Subtlely** [fgprodigal/RayUI#16]
/label ~Bug

**描述**

**重现Bug的步骤**
1.进入战斗时 聊天框的物品鼠标提示会被禁用，鼠标放在物品上没有提示，脱战后鼠标提示会弹出。
2.聊天框黑边 按下enter键弹出聊天框时的描边变黑
3.任务框世界任务进度条不显示 RL后会显示但是条进度不准 疑似只有PVP任务才会出现。
确定是最新版 第一个BUG一直有不过没来得及报 后两个是更新了才有的
**仅启用RayUI**
<!仅开启RayUI时也会出现这个Bug>

**报错内容**

```

```

**Comment by fgprodigal** [comment]
1.为了防止taint，代码就是这么写的
2.没看懂
3.长久以来的问题，待解决

**Comment by Subtlely** [comment]
截图 不知道是否能看的到
![image](https://cloud.githubusercontent.com/assets/23094693/19882821/5cc89148-a04b-11e6-8e32-90df50e41998.png)

**Comment by fgprodigal** [comment]
我下班看看吧
