### ISSUE TITLE
人物界面裝等字體過小

### ISSUE THREAD

**Issue by makcheunghei** [fgprodigal/RayUI#17]
![default](https://cloud.githubusercontent.com/assets/11705182/19886992/e51773a6-a060-11e6-9b9f-318e1b3c8d4d.jpg)

在界面缩放100%和60%也是一样 解析度是3820X2160

**Comment by fgprodigal** [comment]
mbp吗，这种高分辨率确实没考虑，我再适配一下。
还有你这是最新的包吗，主手怎么还是750，鼠标移到自己头像上显示的装等对不对

**Comment by fgprodigal** [comment]
all fixed
