### ISSUE TITLE
25人模式和40人模式判断问题

### ISSUE THREAD

**Issue by ViolyS** [fgprodigal/RayUI#19]
/label ~Bug

**描述**
关于团队layout问题，25人模式和40人模式判断问题
maxPlayers应该为团队最大人数。
不应以maxPlayers<=25为模式判断条件。应以instanceGroupSize实际判断 

**重现Bug的步骤**

1. 第一步
2. 第二步
3. 第三步
4. 第四步

**仅启用RayUI**

**报错内容**

```

```

**Comment by fgprodigal** [comment]
哪个副本会出现问题吗

**Comment by schokoTT** [comment]
pt或者h团队增加26人及以上的时候不显示新添加6队以后的人，需要/rl一下，问题不大。但是我觉得没必要保留两种团队设置。只保留40人团队就行了，团本玩的治疗，并不怎么知道别的职责的需求。

**Comment by ViolyS** [comment]
我在打普通梦魇的时候，因为之前组人组到30人。但是后来有人离队，只有23人，但是还是显示40人模式，重载依然为40人模式。/dump GetInstanceInfo()查询，显示maxPlayers为30，instanceGroupSize为23。

**Comment by makcheunghei** [comment]
希望改善一下 25人團的時侯為了安排分組策略會調往第6 第7小隊 

這時侯不會顯示出來
