### ISSUE TITLE
翡翠梦境M难度老一心控被解救之后画面会卡顿3秒左右

### ISSUE THREAD

**Issue by luos09** [fgprodigal/RayUI#21]
/label ~Bug

**描述**

**重现Bug的步骤**

1. 进入史诗难度的“翡翠梦境”副本第一个boss
2. 自己叠加Debuff“感染意志”到10层之后，自己就会被boss心控，变成和队友相互攻击，自己的血量被队友打到25%左右则解除心控
3. 解除心控的一瞬间，画面就会卡顿三秒左右；
 另：（无伤大雅的一个体验反馈）背包整理与“EUI”或者“ElvUI”对比，比较卡。不知是否有啥不一样的整理逻辑。
最后，感谢一直在更新，辛苦了。谢谢！

**仅启用RayUI**
<仅使用RayUI，无任何修改，并食用前已经清除cache、interface、wtf三个文件夹>

**报错内容**
无报错，仅是画面卡顿。
```

```

**Comment by fgprodigal** [comment]
第一个问题，如果没有报错内容，没法解决，我打不了这么高级的副本，无法凭空修复bug

**Comment by luos09** [comment]
所噶！好的，基本影响不大。
最后还是感谢更新。么哒~

**Comment by schokoTT** [comment]
我只能调低特效 ，觉得可能是姓名板的原因，明天试试删除姓名板打一次。

**Comment by makcheunghei** [comment]
這個是心控後改變陣營做成的卡頓 舊世界任務也是這樣

**Comment by schokoTT** [comment]
删除nameplates文件夹，没有卡顿了！！

**Comment by schokoTT** [comment]
我觉得是敌我血条的问题，一瞬间的事。

**Comment by bskfjhh** [comment]
不用删除的,打M1的时候，你关掉就行了，CTRL+V关了就行了，后面BOSS再开。
我觉得的这个是看电脑的，我卡1秒多点。

**Comment by schokoTT** [comment]
关掉敌对姓名板嘛，下个cd我试试

**Comment by fgprodigal** [comment]
各位更新一下，然后给个反馈

**Comment by schokoTT** [comment]
这个cd打老1心控关闭敌对血条卡顿基本没有了。要测试只能下个cd了。

**Comment by schokoTT** [comment]
老1没问题了，我死皮赖脸混了一次

**Comment by fgprodigal** [comment]
很好
