### ISSUE TITLE
信息条金币统计有误

### ISSUE THREAD

**Issue by billseraph** [fgprodigal/RayUI#22]
/label ~Bug

**描述**
<金币超过100万以后信息条的货币统计有误，显示1亿多>
<另外，神器经验条鼠标移上去会弹出，会关闭成就窗口>

**重现Bug的步骤**
<先赚100万金，然后开插件>
<鼠标中键点击小地图选择成就，在弹出成就窗口后鼠标移动，极易划过神器经验条导致自动关闭成就窗口>

**仅启用RayUI**
<是>

**报错内容**

```
金币超过100W以后信息条内金币统计有误，显示1亿多
```

**Comment by fgprodigal** [comment]
第一个问题先等我几年
第二个问题没办法读神器的数据必须打开神器的窗口，别的窗口就会关闭
