### ISSUE TITLE
最新更新后rl报错

### ISSUE THREAD

**Issue by LeonVons** [fgprodigal/RayUI#26]
/label ~Bug

**描述**

![Uploading 3.png…]()

**重现Bug的步骤**

1. 第一步 RL之后稳定报错。。。
2. 第二步
3. 第三步
4. 第四步

**仅启用RayUI**
是

**报错内容**
Interface\AddOns\RayUI\modules\watcher\watcher.lua:501: attempt to index field '?' (a nil value)
Count: 1

Call Stack:
Interface\AddOns\RayUI\core\functions.lua:762: in function `ThrowError'
Interface\AddOns\RayUI\core\functions.lua:288: in function `InitializeModules'
Interface\AddOns\RayUI\init.lua:96: in function <Interface\AddOns\RayUI\init.lua:61>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...dOns\MeetingStone\Libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...dOns\MeetingStone\Libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...dOns\MeetingStone\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>

```

**Comment by fgprodigal** [comment]
截图看不到，说职业

**Comment by LeonVons** [comment]
职业是DK，上线无报错，RL之后必跳报错

不知道水月君玩不玩DK，有一个想法不知道可不可以实现，希望修改DK符文冷却时的颜色，这样很容易区分还在恢复的符文和就绪的符文，清楚自己手里有多少资源

**Comment by fgprodigal** [comment]
dk的符文不是统一成一种了吗，报错晚点再看

**Comment by LeonVons** [comment]
Interface\AddOns\RayUI\modules\watcher\watcher.lua:501: attempt to index field '?' (a nil value)
Count: 1

Call Stack:
Interface\AddOns\RayUI\core\functions.lua:762: in function `ThrowError'
Interface\AddOns\RayUI\core\functions.lua:288: in function`InitializeModules'
Interface\AddOns\RayUI\init.lua:96: in function <Interface\AddOns\RayUI\init.lua:61>
(tail call): ?

[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...dOns\MeetingStone\Libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...dOns\MeetingStone\Libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...dOns\MeetingStone\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
战斗中的报错
现在DK符文是统一，全是红色的死亡符文，我的意思是将还在恢复中的符文比如改成暗红色，或者可用时高亮。这样才能更简单的区分可用的符文和即将恢复的符文

**Comment by LeonVons** [comment]
![1](https://cloud.githubusercontent.com/assets/23161825/20037155/a6a3ec46-a455-11e6-8ec9-7d8a879a91d0.png)

举个例子，这是si大大的NDUI中，DK的符文部分，还在恢复的符文颜色会稍暗，很容易看出目前有几个符文可用
水月大大的头像也是基于ouf的吧，应该可以达成同样的效果，如果这个请求有所为难，还请见谅！

**Comment by fgprodigal** [comment]
符文改好了，但是你这个报错我重现不了

**Comment by fgprodigal** [comment]
你有自己在控制台加监视的法术吗，或者你更新的时候没有覆盖watcher的配置吗

**Comment by LeonVons** [comment]
watch文件我貌似没更换，这个原因么，我提交几个也是发到这里么

**Comment by fgprodigal** [comment]
https://github.com/fgprodigal/RayUI/commit/2fca69d96aa0f03ef9e0ddb1a24603a8b1bb7eff 自己看看我删了多少东西，你们更新怎么那么喜欢自作主张呢

**Comment by LeonVons** [comment]
抱歉。。。我是World of Warcraft\Interface\Addons\RayUI\config\filters里的watchers没有更换。。。是这个原因么
我这就删了重新放- -
