### ISSUE TITLE
小队模式下依旧显示团队分队

### ISSUE THREAD

**Issue by Subtlely** [fgprodigal/RayUI#35]
**描述**

![image](https://cloud.githubusercontent.com/assets/23094693/20165425/0c6d8e5c-a748-11e6-966c-bb9019d1b5cf.png)
如图，五人本小队时团队框架的小队编号依旧出现，确定没有转化为团队。应该也不算BUG- -但是之前小队模式是没有的，所以想请水月大大修改下，感激不尽
**仅启用RayUI**

确认仅开启RAYUI

**报错内容**

```

```

**Comment by bskfjhh** [comment]
团队下小队编号直接关掉好了
