### ISSUE TITLE
插件错误

### ISSUE THREAD

**Issue by hanyinan1985** [fgprodigal/RayUI#37]
**描述**

![image](https://cloud.githubusercontent.com/assets/17735671/20172134/b8a15aac-a76e-11e6-8b3d-d9d61c3c565c.png)

**重现Bug的步骤**

1.任何游戏内的场景切换，读蓝条完毕后经常出现
2.切换角色进入游戏时会出现

**仅启用RayUI**

仅开启RAYUI

**报错内容**

```
Interface\AddOns\RayUI\modules\skins\skins.lua:155: doesn't exist!
```

**Comment by fgprodigal** [comment]
显然是你看黑市之后报错的，以后贴报错不要只贴一行
