### ISSUE TITLE
最新更新的yClassColor，社交界面职业染色似乎没有生效

### ISSUE THREAD

**Issue by LeonVons** [fgprodigal/RayUI#39]
**描述**

![qq 20161112233648](https://cloud.githubusercontent.com/assets/23161825/20238943/d68a4344-a930-11e6-89c4-41f6ca48ee52.png)

**重现Bug的步骤**

1. 第一步
2. 第二步
3. 第三步
4. 第四步

**仅启用RayUI**

是的

**报错内容**

```
无报错
```

请问这是最新的改动故意去掉的么

**Comment by fgprodigal** [comment]
就是这样的，并且这个插件不是我写的
