### ISSUE TITLE
任务物品问题

### ISSUE THREAD

**Issue by hanyinan1985** [fgprodigal/RayUI#42]
**描述**

刚进入游戏或者/RL后
![image](https://cloud.githubusercontent.com/assets/17735671/20459619/2c7dc974-af03-11e6-8252-eed7cfda2a2e.png)
切换地图读蓝条、炉石、进副本、战场后
![image](https://cloud.githubusercontent.com/assets/17735671/20459617/2584d6ee-af03-11e6-80d0-e35029484437.png)

**重现Bug的步骤**

1. 第一步  任务追踪栏内有可使用的任务物品
2. 第二步  炉石或者进副本、战场触发的读蓝条
3. 第三步  物品颜色变黑
4. 第四步  /RL后恢复正常，再读蓝条（例如炉石或者进副本、战场）后又变黑

**仅启用RayUI**

仅开启RAYUI

**报错内容**

```
任务物品颜色变暗
```

**Comment by fgprodigal** [comment]
你是处女座？

**Comment by hanyinan1985** [comment]
哈哈哈，有可能！

**Comment by hanyinan1985** [comment]
主要是太喜欢这个插件了！！

**Comment by LeonVons** [comment]
你好，请问你这个字体是什么- -

**Comment by hanyinan1985** [comment]
微软雅黑
