### ISSUE TITLE
非BUG问题：请问大大，插件是否集成了反和谐功能？

### ISSUE THREAD

**Issue by luos09** [fgprodigal/RayUI#43]
**描述**
请问一声大，最新版的插件是否集成了反和谐功能？
如果有的话该如何关掉？
家里有妹纸也一起在用同个电脑玩，挺接受不来原汁原味的客户端。
如果有，盼告知；
如果没有，则抱歉打扰了~
此致。

**重现Bug的步骤**

1. 已经重新下载了全新的国服客户端；删除所有插件，非反和谐；
2. 下载rayui之后，wtf文件夹里面的congfig文件会自动多一句SET overrideArchive "0"，经过确认，这个就是反和谐的设置；修改0为1或者删除本命令，修改文件为只读权限，也无法停止；
3. 重新登录，会再次成为SET overrideArchive "0"

**仅启用RayUI**

**报错内容**

```

```

**Comment by fgprodigal** [comment]
我第一次见求和谐的……等我电脑修好再说吧

**Comment by anson0370** [comment]
少年 难道不是给妹纸再买一台电脑好一起玩吗？

**Comment by luos09** [comment]
哈哈，谢谢大人！
我就是求和谐的那一个...
另外：其实我有两台电脑，羞涩的不好意思说求和谐的客户端，所以让妹纸来打掩护。

**Comment by ViolyS** [comment]
在顶部有个搜索，this repository 中搜索overrideArchive
有个结果Interface/AddOns/RayUI/core/functions.lua 
self:LockCVar("overrideArchive", 0)
注释，在删除WTF中的config对应。或者锁定为“1”。

**Comment by luos09** [comment]
谢谢楼上大大~谢谢各位的解答！
