### ISSUE TITLE
关于durability figue 耐久图的小bug

### ISSUE THREAD

**Issue by schokoTT** [fgprodigal/RayUI#44]
**描述**
http://ww1.sinaimg.cn/large/620f958bjw1fa178b2t5sj218g0p0k3i.jpg
http://ww2.sinaimg.cn/large/620f958bjw1fa178cdp1zj218g0p0qf5.jpg
bug就是今天想调整下耐久提示位置，发现并不能调整。
之前被动作条挡到，打团灭到装备耐久为0已经被团长喷了好几回了。
这个小东西能添加在解锁界面元素时修改位置的功能嘛，感谢水月大。

**重现Bug的步骤**

1. 第一步 装备黄了或者红了，上多人坐骑后装备耐久图就会消失。
2. 第二步 骑单人坐骑就没有这种情况
3. 第三步
4. 第四步

**仅启用RayUI**
开启RayUI时也会出现这个Bug

**报错内容**

```木有报错

```

**Comment by fgprodigal** [comment]
我看了一下暴雪的源代码，他自己写的就是有载具的时候不显示耐久
