### ISSUE TITLE
不知道是不是我个人的原因- -但是调试了半天真的找不出来哪里错了- -狂徒贼神器监视无效 

### ISSUE THREAD

**Issue by Subtlely** [fgprodigal/RayUI#52]
**描述**
狂徒贼神器 恐惧之刃的诅咒 开启后是身上出现的DEBUFF，所以我的监视写为
--恐惧之刃诅咒
{ spellID = 202665, unitId = "player", caster = "player", filter = "DEBUFF" },
这个监视在更新7.1.5之前一直可用，但是7.1.5出来之后就莫名其妙无效。自己未做任何修改。
控制台里的法术监视也有这个，不知道能不能表示监视成功
自己看了半天没发现什么问题- -只好来求助一发，恳求水月大大帮忙测试下是否是我个人的问题
感激不尽
**仅启用RayUI**

**报错内容**

```

```

**Comment by fgprodigal** [comment]
caster改成all不是常识吗
