### ISSUE TITLE
一些小BUG 无报错

### ISSUE THREAD

**Issue by Subtlely** [fgprodigal/RayUI#6]
/label ~Bug

**描述**

**重现Bug的步骤**
1.战斗中如果隐藏聊天栏 按下enter键不会自动弹出
2.团队设置里 无论如何设置大小团队框架都不会改变
更新时间为20:00
刚刚手滑了点快了对不起

**仅启用RayUI**
仅开启RayUI时也会出现这个Bug

**报错内容**

```

```

**Comment by fgprodigal** [comment]
？

**Comment by schokoTT** [comment]
大概说的是40人团队的问题吧，我觉得没有必要保留两种团队设置了。
40人团队框架不能改变大小，在fb外面组超过25人显示40人框架挺难看的。
只保留40人团队就不错，25人团队有点落伍了。
团队编号也有点多余。

**Comment by fgprodigal** [comment]
你看到上面的fix和closed了么，团队编号多余你就关掉啊，我把小队从纵向变成横向了，不加个小队编号谁知道
