### ISSUE TITLE
1个bug,1个问题,我都觉得我问题好多....

### ISSUE THREAD

**Issue by zhfish** [fgprodigal/RayUI#60]
放在侧边栏的武器,饰品,在查看时,比较物品窗口会重叠在一起(左手武器,右手武器,当前查看的武器)..放下方的动作条不会重叠

如何从目标的头像中区分普通,稀有,精英?
原来等级后面有+号..

**Comment by schokoTT** [comment]
鼠标指向是定位问题，这个尽量避免吧。

头像里面100r是精英   其实吧这个靠插件来处理就行。npcscan就蛮好嘛
