### ISSUE TITLE
最近两天更新导致Broker_WorldQuests无法使用了。

### ISSUE THREAD

**Issue by Gslw** [fgprodigal/RayUI#7]
/label ~Bug

**描述**

信息条切换到这个模块后鼠标指向无法弹出面板，27号更新前是可以正常使用的。

**重现Bug的步骤**
1. 第一步：安装插件
2. 第二步：信息条切换Broker_WorldQuests
3. 第三步：鼠标指向

**仅启用RayUI**

依旧无法显示并报错

**报错内容**

```
Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:1412: attempt to compare number with nil
Count: 1

Call Stack:
[C]: ?
Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:1412: in function `AttachToBlock'
Interface\AddOns\Broker_WorldQuests\WorldQuests.lua:1536: in function `OnEnter'
Interface\AddOns\RayUI\modules\infobar\infobar.lua:324: in function `tooltipFunc'
Interface\AddOns\RayUI\modules\infobar\infobar.lua:176: in function <Interface\AddOns\RayUI\modules\infobar\infobar.lua:172>

```

**Comment by fgprodigal** [comment]
你提的两个issue我这都重现不了

**Comment by Gslw** [comment]
更新了下背包问题已经修复了。
这个信息条是我这里的问题，插件本身是右键弹出设置菜单，由于RayUI得右键是切换模块没法设置所以我修改默认设置导致的，并不是RayUI的问题，抱歉。

**Comment by fgprodigal** [comment]
broker类信息条shift加右键调用他自己的右键菜单

**Comment by Gslw** [comment]
哦，这样啊。

对了还有个问题，好友信息条的Alt组队好像失效了，会报错。

...ace\AddOns\RayUI\modules\infobar\infobar_friends.lua:57: attempt to call upvalue 'FriendsFrame_HasInvitePermission' (a nil value)
Count: 1

Call Stack:
...nterface\AddOns\RayUI\libs\Tablet-2.0\Tablet-2.0.lua:1016: in function <...nterface\AddOns\RayUI\libs\Tablet-2.0\Tablet-2.0.lua:1001>

**Comment by Gslw** [comment]
谢谢，问题都已解决。
