### ISSUE TITLE
Cooldown Charges.

### ISSUE THREAD

**Issue by ghost** [fgprodigal/RayUI#70]
**描述**

![dwqdwqfqqgqwq](https://user-images.githubusercontent.com/1692977/27466977-7d96d286-57ac-11e7-8275-233028e2181e.PNG)

**重现Bug的步骤**

1. As you can see above the cooldown module does not make up for charges. It should not show a cooldown unless I have used all its charges.
2. 第二步
3. 第三步
4. 第四步

**仅启用RayUI**

This is with RayUI only enabled. Using its built in cooldown module.

**报错内容**

```

```

**Comment by fgprodigal** [comment]
Actually, you can see a little spark circling before all charges is used up

**Comment by ghost** [comment]
There shouldn't be a cooldown until the charges are used up. It is near impossible to tell if the spell is able to be used or not.

**Comment by fgprodigal** [comment]
well...I misunderstood you.I'll check this later.

**Comment by ghost** [comment]
Sorry about that. https://github.com/tullamods/OmniCC does a deal where the cooldown is like in an alpha state if there are still charges once they are used it the cooldown number become 100% visible. So say I have 1 charge left, the cooldown numbers would be like 40% alpha or something.

**Comment by fgprodigal** [comment]
Thanks for your feedback. I will consider how to deal with it after work as soon as possible.
Thank you again! 😄
