### ISSUE TITLE
动作条冷却字体大小不一

### ISSUE THREAD

**Issue by Subtlely** [fgprodigal/RayUI#72]
**描述**

![image](https://user-images.githubusercontent.com/23094693/27515199-be80a74c-59d0-11e7-96dd-9bf04ba77b9c.png)

**重现Bug的步骤**
刚刚更新的发现的问题，之前用的一直没有，如图，字体冷却大小不一，但是充能类技能再次使用后大小又会恢复正常。并且无充能类技能冷却大小暂时没有发现不一样大小的，怀疑这个问题仅存在在充能技能中。

**仅启用RayUI**

仅开启RAYUI

**报错内容**

```
无报错
```

**Comment by fgprodigal** [comment]
这不叫bug，谢谢
