### ISSUE TITLE
watcher 和 小队成员名字消失

### ISSUE THREAD

**Issue by gawainGIT** [fgprodigal/RayUI#97]
**描述**

![wowscrnshot_082118_220307](https://user-images.githubusercontent.com/9333357/44415099-8473b900-a5aa-11e8-9453-42c5c690b5c8.jpg)
![wowscrnshot_082118_233356](https://user-images.githubusercontent.com/9333357/44415589-ce10d380-a5ab-11e8-8b6c-39c1fe965324.jpg)

**重现Bug的步骤**

1. 第一步  现在的watcher没法通过shift加点击右上角的buff实现
2. 第二步  但是可以选中自己shift右键自己头像上的buff实现
3. 第三步  但是他会自动把几乎所有buff放到watcher去，并且取消的时候也是一起取消的

第二张图是  每次有新成员加入的时候都会导致别的成员名字变成空白 

另一个是小地图下面的原来是神器能量那个条，现在是一个不动的白条，我准备照着仿一个
这个版本的项链能量的，但是暂时还没找到api。。

**仅启用RayUI**

**报错内容**

```

```

**Comment by Jerry-Ma** [comment]
https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/AzeriteBar.lua 
神器能量条的API例子，你可以参考下。
